---
- hosts: localhost
  connection: local

  vars_files:
    # - "vars/creds.json"
    # - "vars/params.yml"
    - "vars/hostsAzurePublicIp.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

   - debug: var=all.hosts.controller1.ansible_host
